---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: phone-book
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "secure_root_password_123"
  MYSQL_PASSWORD: "secure_user_password_123"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: phone-book
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: "grafana_admin_123"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: phone-book
type: Opaque
stringData:
  REDIS_PASSWORD: "redis_pass_123"
  JWT_SECRET: "your_jwt_secret_key_here_change_in_production"